import { CURRENCY } from '../constants';

export const CURRENCY_ICON = {
    [CURRENCY.RUB.id]: '₽',
    [CURRENCY.USD.id]: '$',
    [CURRENCY.EUR.id]: '€',
    [CURRENCY.KZT.id]: '₸',
    [CURRENCY.UAH.id]: '₴',
    [CURRENCY.CNY.id]: '¥',
    [CURRENCY.GBP.id]: '£',
    [CURRENCY.CHF.id]: '₣',
    [CURRENCY.JPY.id]: '¥',
    [CURRENCY.CAD.id]: 'CA$',
    [CURRENCY.AUD.id]: 'A$',
    [CURRENCY.NZD.id]: 'NZ$',
    [CURRENCY.SEK.id]: 'kr',
    [CURRENCY.NOK.id]: 'kr',
    [CURRENCY.PLN.id]: 'zł',
    [CURRENCY.MXN.id]: 'MX$',
    [CURRENCY.INR.id]: '₹',
    [CURRENCY.BRL.id]: 'R$',
    [CURRENCY.TRY.id]: '₺',
    [CURRENCY.RON.id]: 'lei',
    [CURRENCY.CZK.id]: 'Kč',
    [CURRENCY.HRK.id]: 'kn',
    [CURRENCY.BGN.id]: 'лв',
    [CURRENCY.ISK.id]: 'kr',
    [CURRENCY.CLP.id]: 'CLP',
    [CURRENCY.PHP.id]: '₱',
    [CURRENCY.AED.id]: 'AED',
    [CURRENCY.SAR.id]: 'SAR',
    [CURRENCY.KRW.id]: '₩',
    [CURRENCY.HKD.id]: 'HK$',
    [CURRENCY.SGD.id]: 'S$',
    [CURRENCY.MYR.id]: 'RM',
    [CURRENCY.IDR.id]: 'Rp',
    [CURRENCY.THB.id]: '฿',
};
